### ISSUE TITLE
I have a trouble with build

### ISSUE THREAD

**Issue by Sanceilaks** [kuragehime/source-base#1]
When I do `cargo check -Zbuild-std`, I get this error

> error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
> See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.

Okey, no problem, lets use nightly toolchain `cargo +nightly check -Zbuild-std`
Result: 
> error: failed to run `rustc` to learn about target-specific information
> 
> Caused by:
>   process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target \\?\D:\VSP\rust\source-base\targets\i686-pc-windows-minicrt.json --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
>   --- stdout
>   ___.exe
>   lib___.rlib
>   ___.dll
>   ___.dll
>   ___.lib
>   ___.dll
>   C:\Users\Admin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc
>   debug_assertions
>   panic="unwind"
>   proc_macro
>   target_abi=""
>   target_arch="x86"
>   target_endian="little"
>   target_env="msvc"
>   target_family="windows"
>   target_feature="fxsr"
>   target_feature="llvm14-builtins-abi"
>   target_feature="sse"
>   target_feature="sse2"
>   target_has_atomic="16"
>   target_has_atomic="32"
>   target_has_atomic="64"
>   target_has_atomic="8"
>   target_has_atomic="ptr"
>   target_has_atomic_equal_alignment="16"
>   target_has_atomic_equal_alignment="32"
>   target_has_atomic_equal_alignment="64"
>   target_has_atomic_equal_alignment="8"
>   target_has_atomic_equal_alignment="ptr"
>   target_has_atomic_load_store="16"
>   target_has_atomic_load_store="32"
>   target_has_atomic_load_store="64"
>   target_has_atomic_load_store="8"
>   target_has_atomic_load_store="ptr"
>   target_os="windows"
>   target_pointer_width="32"
>   target_vendor="pc"
>   windows
> 
>   --- stderr
>   error: `-Csplit-debuginfo=packed` is unstable on this platform
> 
>   error: aborting due to previous error

And `cargo +nightly check -Zunstable-options -Zbuild-std` do not help
Maybe you have a solution?

**Comment by kuragehime** [comment]
Umm.. im sorry i have no idea, i'm using nightly 1.64 if that can help, try installing this version maybe? and try running the build command in a Visual Studio Developer Command Prompt, that fixes some issues such as rustc not being able to find the linker or some libraries

**Comment by Sanceilaks** [comment]
Okay, I fixed that. Just remove line `"split-debuginfo": "packed",` from `i686-pc-windows-minicrt.json`
